### ISSUE TITLE
Errors when executing yarn watch or yarn build 

### ISSUE THREAD

**Issue by daniellee** [atosorigin/grafana-weathermap-panel#4]
When following the build instructions in the readme, the `yarn watch` and `yarn build` commands throw errors.

Steps to recreate:
1. git cloned the repository into the Grafana plugins directory
2. There is no yarn lockfile. Just followed the instructions and executed `yarn install`
3. Executed yarn watch and got the following error: 
```
Compilation failed!
  ./module.ts
  Error: [BABEL] /home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/src/module.ts: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@babel/preset-env/lib/index.js")
```

Executing `yarn build` returns thousands of prettier errors. Here is the end of the error report:

```
442:1   error  Replace `↹↹↹↹↹↹{⏎↹↹↹↹↹↹↹!this.props.uneCoor.textObj.isTextRegion·&&⏎↹↹↹↹↹↹↹<div·style={styleTextDiv}>⏎↹↹↹↹↹↹↹↹{this.props.uneCoor.label}⏎↹↹↹↹↹↹↹</div>⏎↹↹↹↹↹↹` with `··············{!this.props.uneCoor.textObj.isTextRegion·&&·<div·style={styleTextDiv}>{this.props.uneCoor.label}</div>`      prettier/prettier
    448:1   error  Replace `↹↹↹↹↹↹` with `··············`       prettier/prettier
    449:1   error  Replace `↹↹↹↹↹` with `············`       prettier/prettier
    450:1   error  Replace `↹↹↹↹</Tooltip>` with `··········</Tooltip>⏎········)`       prettier/prettier
    451:1   error  Replace `↹↹↹}⏎↹↹↹` with `······}`       prettier/prettier
    453:1   error  Replace `↹↹` with `····`       prettier/prettier
    454:1   error  Replace `↹}` with `··};`       prettier/prettier
    454:3   error  Missing semicolon       @typescript-eslint/semi
    456:1   error  Replace `↹` with `··`       prettier/prettier
    457:1   error  Replace `↹` with `··`       prettier/prettier
    457:2   error  Public accessibility modifier on method definition render       @typescript-eslint/explicit-member-accessibility
    458:1   error  Replace `↹↹return·(⏎↹↹↹<div>⏎↹↹↹↹{this.state.htmlResult}⏎↹↹↹</div·>⏎↹↹)` with `····return·<div>{this.state.htmlResult}</div>`       prettier/prettier
    463:1   error  Replace `↹` with `··`       prettier/prettier

  ✖ 13314 problems (13314 errors, 0 warnings)
    12703 errors and 0 warnings potentially fixable with the `--fix` option.



  Trace: Error: 13314 linting errors found in 90 files
      at /home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:117:31
      at step (/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.next (/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at fulfilled (/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:107:62)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at /home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/home/daniel/dev/go/src/github.com/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
✖ 13314 linting errors found in 90 files
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Node version: v12.13.1
Yarn version: 1.21.1
OS: Ubuntu 16.04

**Comment by daniellee** [comment]
The line ending errors are probably due to this breaking change in Prettier 2.0 if you have line endings set to crlf rather than lf: https://github.com/prettier/prettier/issues/6932

**Comment by hellosct1** [comment]
thank you
we're looking at this

**Comment by KatKofil** [comment]
Hello,
I've try to reproduce with this step:
 - install a new VM with Debian GNU/Linux (buster)
 - install go version 1.14.1
 - install node v12.16.1
 - install npm 6.13.4
 - install grafana :
    ```
     go get github.com/grafana/grafana
     go run build.go setup
     go run build.go build
     yarn install
     yarn start
     make run
```
 - install plugin :
    - `git clone https://github.com/atosorigin/grafana-weathermap-panel.git`
    - `yarn watch`

and get no error.
I got error on build we working on.
If you have more information about the fail of yarn watch it will be great.
Thanks to help us by testing.

**Comment by hellosct1** [comment]
Hi, 

I managed to fix the problem
now it works and it compiles correctly

@daniellee I'm updating the repository

thanks

**Comment by ZUID1908** [comment]
Hi,

I.m running Ubuntu 18.04.4 LTS, node v12.16.1 and npm 6.13.4. and updated plugin to version 0.4.2.
After "yarn build" I still get thousands of prettier/prettier errors, example:

     228:1   error  Replace `â†¹â†¹` with `Â·Â·Â·Â·`                                                prettier/prettier
    229:1   error  Replace `â†¹}` with `Â·Â·};`                                                prettier/prettier
    229:3   error  Missing semicolon                                                       @typescript-eslint/semi
    231:1   error  Replace `â†¹` with `Â·Â·`                                                   prettier/prettier
    232:1   error  Replace `â†¹` with `Â·Â·`                                                   prettier/prettier
    233:1   error  Replace `â†¹` with `Â·Â·`                                                   prettier/prettier
    234:1   error  Replace `â†¹` with `Â·Â·`                                                   prettier/prettier
    235:1   error  Replace `â†¹` with `Â·Â·`                                                   prettier/prettier
    235:2   error  Public accessibility modifier on method definition deleteArrayLinkCLass                                                                                                                             @typescript-eslint/explicit-member-accessibility
    236:1   error  Replace `â†¹â†¹constÂ·newLinkClass:Â·LinkClass[]Â·=Â·this.state.arrayLinkClassâŽâ†¹â†¹â†¹.filter((value:Â·LinkClass)Â·=>âŽâ†¹â†¹â†¹â†¹value.idÂ·!==Â·idâŽâ†¹â†¹â†¹` with `Â·Â·Â·Â·constÂ·newLinkClass:Â·LinkClass[]Â·=Â·this.state.arrayLinkClass.filter((value:Â·LinkClass)Â·=>Â·value.idÂ·!==Â·id`                                                                            prettier/prettier
    240:1   error  Replace `â†¹â†¹` with `Â·Â·Â·Â·`                                                prettier/prettier
    241:1   error  Replace `â†¹â†¹â†¹` with `Â·Â·Â·Â·Â·Â·`                                             prettier/prettier
    242:1   error  Replace `â†¹â†¹` with `Â·Â·Â·Â·`                                                prettier/prettier
    243:1   error  Replace `â†¹â†¹` with `Â·Â·Â·Â·`                                                prettier/prettier
    244:1   error  Replace `â†¹â†¹â†¹` with `Â·Â·Â·Â·Â·Â·`                                             prettier/prettier
    245:1   error  Replace `â†¹â†¹` with `Â·Â·Â·Â·`    ^Z
[3]+  Stopped                 yarn build 

Thank you!

**Comment by KatKofil** [comment]
We still working on error about yarn build. We will push asap a patch to correct linting error.

**Comment by hellosct1** [comment]
HI @daniellee @ZUID1908 

it's good

the manual installation has been updated and now it all works

thank you in advance for the review

**Comment by ZUID1908** [comment]
Hi @hellosct1 

Thanks for the update! I still seem to have an error:
root@grafana:/var/lib/grafana/plugins/grafana-weathermap-panel# yarn build

yarn run v1.22.4
$ grafana-toolkit plugin:build
âœ” Preparing
â ‹ Linting  Trace: Error: Failed to load config "prettier" to extend from.
  Referenced from: /var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
      at configMissingError (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:264:9)
      at ConfigArrayFactory._loadExtendedShareableConfig (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:824:23)
      at ConfigArrayFactory._loadExtends (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:729:25)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
      at _normalizeObjectConfigDataBody.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigData (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
      at _normalizeObjectConfigData.next (<anonymous>)
      at ConfigArrayFactory._normalizeObjectConfigDataBody (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/eslint/lib/cli-engine/config-array-factory.js:697:25) {
    messageTemplate: 'extend-config-missing',
    messageData: {
      configName: 'prettier',
      importerName: '/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js'
    }
  }
      at /var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
âœ– Failed to load config "prettier" to extend from.
Referenced from: /var/lib/grafana/plugins/grafana-weathermap-panel/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by KatKofil** [comment]
Hi @ZUID1908,
https://github.com/prettier/eslint-plugin-prettier/issues/253
It's look like you haven't "eslint-config-prettier" i've fix the package. This will be push soon here.
You can also use `yarn add --dev eslint-config-prettier` to fix it.

**Comment by hellosct1** [comment]
Hi @ZUID1908 @daniellee 

it's good

✔ Compiling...
Done in 45.56s.


Thanks

**Comment by ZUID1908** [comment]
Hi @hellosct1,

It works indeed, thanks!  
âœ” Compiling...
Done in 33.21s.

**Comment by hellosct1** [comment]
Hi,
I close the ticket since this problem is solved
I just released a new version that you can test
The version tested is 0.4.11 @daniellee @ZUID1908
